---
driver:
  name: docker
  privileged: true

driver_config:
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  require_chef_omnibus: false

platforms:
- name: ubuntu-14.04
  provisioner:               
    name: chef_solo          
    chef_omnibus_root: '/usr'

suites:
  - name: a
    run_list:
      - recipe[quagga-test::default_a]
    attributes: 
      quagga: 
        enable_reload: false
  - name: b
    run_list:
      - recipe[quagga-test::default_b]
